import Head from "next/head";
import { fetchCategories } from "../utils/fetchCategories";
import { GetServerSideProps, GetStaticProps } from "next";
import { fetchProducts } from "@/utils/fetchProducts";
import Basket from "@/components/Basket";
import { fetchParentProducts } from "@/utils/fetchParentProducts";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { fetchFlags } from "@/utils/fetchFlags";
import { DISABLE_INVENTORY_FLAG } from "@/constants/flags";
import { sanityClient } from "@/lib/sanity";
import { queryFlags } from "@/utils/queries";

interface Props {
  categories: Category[];
  parentProducts: ParentProduct[];
  products: Product[];
  flags: Flag[];
}

export default function Home({
  categories,
  parentProducts,
  products,
  flags,
}: Props) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);

  if (!mounted) return null;

  const inventoryDisabledFlag = flags.find(
    (flag) => flag.name === DISABLE_INVENTORY_FLAG,
  );

  const DynamicProductPanel = dynamic(
    () => import("../components/ProductPanel"),
    {
      loading: () => <p>Loading...</p>,
    },
  );

  const DynamicHeader = dynamic(() => import("../components/Header"), {
    loading: () => <p>Loading...</p>,
  });

  const DynamicLanding = dynamic(() => import("../components/Landing"));
  return (
    <div>
      <Head>
        <title>Crochetva PlushPals</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="Logo2.png" />
      </Head>

      <DynamicHeader />

      <Basket />

      <main className="relative h-[200vh] min-h-screen">
        <DynamicLanding />
      </main>
      <section className="relative z-40 -mt-[100vh] min-h-screen bg-[#fcf4f4]">
        <DynamicProductPanel
          categories={categories}
          parentProducts={parentProducts}
          products={products}
          inventoryEnabled={!inventoryDisabledFlag?.enabled ?? true}
        />
      </section>
    </div>
  );
}

// Backend Code to Sanity
export const getStaticProps: GetStaticProps<Props> = async () => {
  const categories = await fetchCategories();
  const parentProducts = await fetchParentProducts();
  const products = await fetchProducts();
  const flags = await sanityClient.fetch(queryFlags);

  return {
    props: {
      categories,
      parentProducts,
      products,
      flags,
    },

    // Next.js will attempt to regenerate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    // This helps with caching the data
    revalidate: 10,
  };
};
